targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: ula|lib/screen/service/schema/schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: ula|lib/screen/service/schema/schema.graphql